language = "typescript"
description = "TypeScript connector for HubSpot CRM API (v3)"
post_install_print = """
🚀 Next steps for your HubSpot connector:

📂 Go to your connector directory:
    $ cd {destination_dir}

📖 Read the documentation:
    • Check out README.md for overview and setup
    • Review docs/getting-started.md for detailed instructions
    • See examples/basic-usage.ts for implementation examples
"""