language = "typescript"
description = "TypeScript connector for meta-ads-new"
post_install_print = """
🚀 Next steps to get your meta-ads-new connector running:

📂 Go to your connector directory:
    $ cd 

📦 Install dependencies:
    $ npm install

🔧 Build the connector:
    $ npm run build

🧪 Run tests:
    $ npm test

📖 Next, check out the documentation:
    • Review docs/getting-started.md for configuration details
    • See examples/ for usage examples
    • Update src/connector.ts with your API implementation

🔗 Integration options:
    • Add to your project: import { createConnector } from '@workspace/connector-meta-ads-new'
    • Use with pipelines: Configure as a source in your pipeline setup
    • Standalone usage: Check examples/basic-usage.ts
"""
