# This file was auto-generated by the framework. You can add data models or change the existing ones

from moose_lib import OlapTable, OlapConfig
from pydantic import BaseModel
from datetime import datetime


class MachineData(BaseModel):
    timestamp: datetime
    enterprise: str
    region: str
    country: str
    site: str
    location: str
    line: str
    machine: str
    machine_type: str
    sensor_type: str
    sensor_tag: str
    value: float


# Create the OLAP table
MachineDataTable = OlapTable[MachineData](
    "MachineData",
    OlapConfig(
        order_by_fields=["timestamp"]
    )
)
