# Auto-generated QVD models
#
# This file will be generated by init_qvd.py
# Run: python init_qvd.py --generate-models --source <path>
#
# Example:
#   python init_qvd.py --generate-models --source /path/to/qvd
#   python init_qvd.py --generate-models --source s3://bucket/qvd-files

# Models will appear here after generation
