language = "typescript"
description = "TypeScript connector for Dutchie API (v001)"
post_install_print = """
🚀 Next steps for your Dutchie connector:

Set the environment variable in your shell:
    DUTCHIE_API_KEY=<your_api_key>

Then, use in your application!

📖 Read the documentation:
    • Review docs/getting-started.md for detailed instructions
    • Check out README.md for overview and setup
"""