import { ConnectorScaffoldTrees } from "@/components/scaffold-tree";

export default function ConnectorScaffoldPage() {
  return (
    <div className="prose dark:prose-invert prose-neutral max-w-none">
      <h1>Connector Scaffold</h1>
      <p>
        Below is a visualization of the connector registry scaffolds. Each
        section shows the folder layout generated by the scaffold and the intent
        of the key folders.
      </p>
      <ConnectorScaffoldTrees />

      <h2>What the folders mean</h2>

      <h3>{`{connector}/_meta`}</h3>
      <ul>
        <li>Holds connector-level metadata that is provider-agnostic.</li>
        <li>
          <strong>Files</strong>: `connector.json`, `README.md`, and `assets/`
          for shared logos/images.
        </li>
        <li>
          Do not place documentation here; documentation belongs with the
          language implementation directories.
        </li>
      </ul>

      <h3>{`{connector}/{version}/_meta`}</h3>
      <ul>
        <li>Version-level metadata for the connector.</li>
        <li>
          <strong>Files</strong>: `version.json`, `README.md`, and `assets/`.
        </li>
      </ul>

      <h3>{`{connector}/{version}/{author}/_meta`}</h3>
      <ul>
        <li>Provider/author-specific metadata and assets.</li>
        <li>
          <strong>Files</strong>: `connector.json` (capabilities, languages),
          `CHANGELOG.md`, `LICENSE`, `assets/`.
        </li>
      </ul>

      <h3>Language implementations under {`{connector}/{version}/{author}`}</h3>
      <ul>
        <li>
          `typescript/{`{implementation}`}/` (and optionally `python/` if
          provided) contain the runnable implementation.
        </li>
        <li>
          Follow these conventions:
          <ul>
            <li>
              `docs/` for human-facing guides (getting started, configuration,
              limits, schema docs)
            </li>
            <li>
              `schemas/` at the top level of the language directory for
              machine-readable definitions and related Markdown
            </li>
            <li>
              `src/` for code with subfolders like `auth/`, `extract/`,
              `transform/`, `load/`
            </li>
            <li>`tests/` for unit tests</li>
            <li>`examples/` for usage samples</li>
          </ul>
        </li>
      </ul>

      <h2>Notes</h2>
      <ul>
        <li>
          `_meta` folders should not include docs; keep docs with the
          language-specific implementation.
        </li>
        <li>
          Schemas should live at the top level of each language implementation
          (not under `src`).
        </li>
      </ul>
    </div>
  );
}
